### ISSUE TITLE
Progress badge doesn't render correctly in Safari

### ISSUE THREAD

**Issue by quentinms** [seriousben/badges#11]
example URL: https://badges.seriousben.com/progress?percent=42

<img width="752" alt="Screen Shot 2022-12-22 at 15 20 19" src="https://user-images.githubusercontent.com/928878/209154412-2c6a39c3-4346-4669-a1fb-1d888a9e0a3f.png">

I don't see any errors in the console, and I'm not familiar enough with SVG to know what's wrong.

Tested on Safari `Version 16.2` (on macOS Monterrey `12.6.2 (21G320)`) and Safari Tech Preview (`Release 160 (Safari 16.4, WebKit 17615.1.14.3)`), getting the same result on iOS 16.2.

No problem with Firefox or Chrome.

**Comment by seriousben** [comment]
Thanks for the bug report, I will be looking into it.

**Comment by seriousben** [comment]
A fix for this was merged. This should get deployed within 24h.

**Comment by quentinms** [comment]
Works for me now. Thanks a lot!
